### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by bbanbury** [andrewhaoyu/TOP#1]
Hi there,
I'm having trouble getting the package installed on my cluster. I've tried multiple versions of R (3.2/3/4) and tried to install via devtools::install_github as directed in the vignette as well as by source.  I get the following error:

Error: package or namespace load failed for ‘TOP’ in library.dynam(lib, package, package.lib):
 shared object ‘bc2.so’ not found
Error: loading failed
Execution halted

I'm happy to share the entire Error if it is helpful.  
Thanks for any assistance,
Barb

**Comment by andrewhaoyu** [comment]
Hi Barb,
Thanks a lot for catching that error! I previously mis-uploaded a development version which causes this install error. I have fixed that bug and tested it on clusters and my local computers. It works well. 
Let me know whether you can install it now.
Thanks again！
Best,
Haoyu

**Comment by bbanbury** [comment]
It works great, thank you for helping so quickly!! 
Barb

**Comment by andrewhaoyu** [comment]
You are welcome! Let me know if you get additional questions.
Haoyu
