### ISSUE TITLE
Cannot install the package 

### ISSUE THREAD

**Issue by florakm** [andrewhaoyu/TOP#2]
Hi Haoyu, 
I am trying to install the package on our cluster and got an error message because I was not able to install CompQuadForm. I am not sure whether this is a problem of my lib or cluster or the package. Have you ever seen it? I am pasting all of the message I have. 
Thank you very much!
Flora

devtools::install_github("andrewhaoyu/TOP", auth_token=NULL)
Downloading github repo andrewhaoyu/TOP@master
Installing TOP
Installing 1 packages: CompQuadForm
Installing package into ‘/home/cqu/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/CompQuadForm_1.4.3.tar.gz'
Content type 'application/x-gzip' length 16638 bytes (16 KB)
==================================================
downloaded 16 KB

* installing *source* package ‘CompQuadForm’ ...
** package ‘CompQuadForm’ successfully unpacked and MD5 sums checked
** libs
g++ -I/app/R/3.2.2/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c imhof.cpp -o imhof.o
imhof.cpp:10:12: error: ‘std::atan’ has not been declared
 using std::atan;
            ^
imhof.cpp:11:12: error: ‘std::exp’ has not been declared
 using std::exp;
            ^
imhof.cpp:12:12: error: ‘std::sin’ has not been declared
 using std::sin;
            ^
imhof.cpp: In function ‘double theta(double*, double*, int*, double*, double*, double*)’:
imhof.cpp:23:59: error: ‘atan’ is not a member of ‘std’
     for (i = 1; i <= m; i = i + 1) sum = sum + h[i - 1] * std::atan(lambda[i - 1] * u[0]) + delta2[i - 1] * lambda[i 
                                                           ^
imhof.cpp:23:59: note: suggested alternative:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /app/R/3.2.2/lib/R/include/R.h:28,
                 from imhof.cpp:7:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:58:1: note:   ‘atan’
 __MATHCALL (atan,, (_Mdouble_ __x));
 ^
imhof.cpp: In function ‘double rho(double*, double*, int*, double*, double*)’:
imhof.cpp:34:116: error: ‘exp’ is not a member of ‘std’
 i = 1; i <= m; i = i + 1)  prod = prod * R_pow(1.0 + R_pow(lambda[i - 1] * u[0], 2.0), 0.25 * h[i - 1]) * std::exp(0.
                                                                                                           ^
imhof.cpp:34:116: note: suggested alternative:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /app/R/3.2.2/lib/R/include/R.h:28,
                 from imhof.cpp:7:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:100:1: note:   ‘exp’
 __MATHCALL (exp,, (_Mdouble_ __x));
 ^
imhof.cpp: In function ‘double imhoffunc(double*, double*, int*, double*, double*, double*)’:
imhof.cpp:45:12: error: ‘sin’ is not a member of ‘std’
     res = (std::sin(theta(u, lambda, lambdalen, h, x, delta2))) / (u[0] * rho(u, lambda, lambdalen, h, delta2));
            ^
imhof.cpp:45:12: note: suggested alternative:
In file included from /usr/include/features.h:374:0,
                 from /usr/include/stdlib.h:24,
                 from /app/R/3.2.2/lib/R/include/R.h:28,
                 from imhof.cpp:7:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:65:1: note:   ‘sin’
 __MATHCALL (sin,, (_Mdouble_ __x));
 ^
make: *** [imhof.o] Error 1
ERROR: compilation failed for package ‘CompQuadForm’
* removing ‘/home/cqu/R/x86_64-pc-linux-gnu-library/3.2/CompQuadForm’

The downloaded source packages are in
	‘/tmp/RtmprV7T79/downloaded_packages’
'/app/R/3.2.2/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  CMD INSTALL '/tmp/RtmprV7T79/devtools77c26a217aeb/andrewhaoyu-TOP-3c5bed7'  \
  --library='/home/cqu/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

ERROR: dependency ‘CompQuadForm’ is not available for package ‘TOP’
* removing ‘/home/cqu/R/x86_64-pc-linux-gnu-library/3.2/TOP’
Error: Command failed (1)
In addition: Warning message:
In utils::install.packages(pkgs, repos = repos, type = type, ...,  :
  installation of package ‘CompQuadForm’ had non-zero exit status
>

**Comment by andrewhaoyu** [comment]
Hi Flora,
Thanks for pointing it out! It's the first time I see this error. It looks like the 'CompQuadForm' can't be installed. Can you try whether the 'CompQuadForm' package be installed using the command install.packages("CompQuadForm")? 
Haoyu

**Comment by florakm** [comment]
Hi Haoyu, 
Thank you for your quick response. I had already tried install.packages("CompQuadForm") before I sent your the message. Unfortunately, I still have the same problem. I don't think there is anything wrong with your package, but I couldn't install it without CompQuadForm. I am trying to figure out whether it is  the package or my libs. 
Thanks
Flora

**Comment by andrewhaoyu** [comment]
Hi Flora,

I just tested only installing the package CompQuadForm. It works fine both my local computer and clusters. So it's probably due to some inconsistency between the package and your libs. The TOP package only requires the CompQuadForm package in one function called DisplayMixedScoreTestResult.  Without the CompQuadForm package, most of the functions in TOP could still work. I have just created another Github package called TESTVERSION_TOP (https://github.com/andrewhaoyu/TESTVERSION_TOP). In this package, I removed the dependency of CompQuadForm. You can install this package with the command install_github("andrewhaoyu/TESTVERSION_TOP"). You can first use this version without CompQuadForm. This version should work for fixed-effect two-stage polytomous model. But for mixed-effect two-stage polytomous model, we indeed need the CompQuadForm to calculate the p-value. 

Best,
Haoyu
